# Jekyll: global configuration
url: https://www.yhi.moe
baseurl:
timezone: UTC
permalink: none # /:categories/:title:output_ext
theme: minima
include:
  - _redirects
exclude:
  - README.md
  - LICENSE*

# Jekyll: plug-ins
# Note: jekyll-feed and jekyll-seo-tags are forcibly enabled by Minima.
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-git_metadata
feed:
  excerpt_only: true

# Minima: site-wide
title: Hello from Junde Yhi
author:
  name: Junde Yhi
  email: anVuZGVAeWhpLm1vZQo=
description: >-
  Junde Yhi's personal World Wide Web portal.
header_pages:
  - about.md
  - blog.md
  - projects.md
  - friends.md
show_excerpts: true

# Minima: theme-wide (namespaced site-wide)
minima:
  skin: classic
  social_links:
    telegram: jundeyhi
    github: jyhi
    twitter: lmy441900
    mastodon:
      - username: jyhi
        instance: comfy.social
