gem "jekyll", "~> 4.2"
gem "minima", :git => "https://github.com/lmy441900/minima", :branch => "self-use"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-git_metadata", :git => "https://github.com/ctrlgroup/jekyll-git_metadata"
